### ISSUE TITLE
Feedback on v1.1

### ISSUE THREAD

**Issue by jsatec-pm** [pwc-technology-be/EU-CAPTCHA#78]
Hi,
Thank you for the delivery of the 1.1.
Thank you for providing a simple html+js page is provided without java dependencies (no jsp) which helped us to go further in our integration and testing than in version 1.0.
However we are facing a blocking issue to go further as we are blocked by the CORS filter to test in our local environment unless we deploy the page on a web server which is not practical and time consuming. 
Would you be able to support for us developing in local (we thought that the CORS filter issue was fixed).
Kind regards,

**Comment by YvesMeersmans** [comment]
Could you please describe your current architecture of your local architecture (where are your calls requested from?) and tell us how your desired set up would be? We have a hard time currently understanding your suggestion.

**Comment by jsatec-pm** [comment]
To summarize our issue, we tried to open the html page that you provided as an example but nothing was happening, there was not even a call to any url of the backend and no instruction on how to configure that.
We guess that we need to wait for a proper documentation where the configuration of the front end and backend will be explained and how to parametrize both components.
We are using Angular in the front end calling a backend via REST-API , all running on Weblogic.

**Comment by YvesMeersmans** [comment]
Thanks for your continued interest.

Every situation and infrastructure is different, which is why we allow you to configure the back end yourself. From the documentation:
"In the example the URL 'http://localhost:8080/’ is used. For a production environment this URL should be changed into the correct server URL and server port corresponding to your server setup and infrastructure. The server URL should be for the server where the application is deployed on. The server port should be the same as for which the application is listening for incoming messages (e.g. https//www.myserver.com: 8082)."

I suggest to try with these new instructions. If that does not work, please hold on until the managed service is launched. We almost reached the point where we can start a PoC. We expect the service to be live anytime between now and Q4 2021.

**Comment by YvesMeersmans** [comment]
@jsatec-pm Please test this once more in a short while when we submit the latest updates to this GitHub, and please notify us if you have further issues.
